apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: buildah-ricp-
  namespace: diploe2-ricp
spec:
  taskRef:
    name: buildah
  params:
    - name: IMAGE
      value: 'docker.io/sacnavi/adoptpetsvc:v8'
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: 'vfs'
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace-ricp
    - name: dockerconfig
      secret:
        secretName: dockerconfig-secret
