apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ci
  namespace: diploe2-ricp
spec:
  description: |
    This pipeline fetches code from a repository, compiles and packages it and creates and
    pushes the container image to image registry.
  params:
    - name: repo-url
      type: string
    - name: maven-image
      type: string
    - name: container-image
      type: string
  workspaces:
    - name: workspace
    - name: maven-settings
    - name: dockerconfig
  tasks:
    - name: fetch-code
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: workspace
    - name: maven-build
      taskRef:
        name: maven
      runAfter:
        - fetch-code
      params:
        - name: GOALS
          value:
            - -B
            - -DskipTests
            - clean
            - package
        - name: MAVEN_IMAGE
          value: $(params.maven-image)
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: workspace
        - name: maven-local-repo
          workspace: workspace
    - name: container-image
      taskRef:
        name: buildah
      runAfter:
        - maven-build
      params:
        - name: IMAGE
          value: $(params.container-image)
        - name: TLSVERIFY
          value: 'false'
        - name: STORAGE_DRIVER
          value: 'vfs'
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
