apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: adoptpet-svc-serverless
spec:
  template:
    spec:
      containers:
        - image: sacnavi/adoptpetsvc:v5
          ports:
            - containerPort: 8079
          env:
            - name: APP_DB
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbname
            - name: APP_USER
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbuser
            - name: APP_PASS
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbpassword
            - name: APP_DB_URL
              value: mongodb://${APP_USER}:${APP_PASS}@adoptpet-db:27017/{APP_DB}?authSource=admin
