apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptpet-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adoptpet-db
  template:
    metadata:
      labels:
        app: adoptpet-db
    spec:
      containers:
        - name: adoptpet-db
          image: sacnavi/adoptpetdb:v1
          ports:
            - containerPort: 27017
          env:
            - name: APP_DB
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbname
            - name: APP_USER
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbuser
            - name: APP_PASS
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbpassword
          volumeMounts:
            - name: adoptpet-db-storage
              mountPath: /data/db
      volumes:
        - name: adoptpet-db-storage
          persistentVolumeClaim:
            claimName: adoptpet-db-pvc
