apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoptpet-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adoptpet-svc
  template:
    metadata:
      labels:
        app: adoptpet-svc
    spec:
      containers:
        - name: adoptpet-svc
          image: sacnavi/adoptpetsvc:v6
          ports:
            - containerPort: 8079
          env:
            - name: APP_DB
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbname
            - name: APP_USER
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbuser
            - name: APP_PASS
              valueFrom:
                 secretKeyRef:
                   name: adoptpet-secrets
                   key: dbpassword
            - name: APP_DB_URL
              value: mongodb://${APP_USER}:${APP_PASS}@adoptpet-db:27017/${APP_DB}?authSource=admin
